### ISSUE TITLE
Multiple versions of keyring found

### ISSUE THREAD

**Issue by Ben-Tai** [cennznet/crml-identity.js#3]
getting an error when trying to run the code example. 

ExtError: Multiple versions of @plugnet/keyring detected, ensure that there is only version one in your dependency tree

I checked package-lock.json and can only find reference to one version `@plugnet/keyring": { "version": "0.90.100`

**Comment by ianhe8x** [comment]
Can you try set a breakpoint at assertSingletonPackage.js in `@plugnet/util` so you can tell why it throws this error. In some cases, for example if you are using hot reload, it might trigger this error. If this is the case, you can try clean `_global.__plugnetjs` manually each hot reloads.

We will consider maybe it would be better just print a warning instead of throw error.

**Comment by ianhe8x** [comment]
Close since no more reports of this issue after the latest release of `@cennznet/api` and `@plugnet/*`.
